# coding: utf-8

"""
    Nexus Repository Manager REST API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 3.20.1-01
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from nexus_api_python_client.configuration import Configuration


class DockerProxyAttributes(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'index_type': 'str',
        'index_url': 'str'
    }

    attribute_map = {
        'index_type': 'indexType',
        'index_url': 'indexUrl'
    }

    def __init__(self, index_type=None, index_url=None, local_vars_configuration=None):  # noqa: E501
        """DockerProxyAttributes - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._index_type = None
        self._index_url = None
        self.discriminator = None

        if index_type is not None:
            self.index_type = index_type
        if index_url is not None:
            self.index_url = index_url

    @property
    def index_type(self):
        """Gets the index_type of this DockerProxyAttributes.  # noqa: E501

        Type of Docker Index  # noqa: E501

        :return: The index_type of this DockerProxyAttributes.  # noqa: E501
        :rtype: str
        """
        return self._index_type

    @index_type.setter
    def index_type(self, index_type):
        """Sets the index_type of this DockerProxyAttributes.

        Type of Docker Index  # noqa: E501

        :param index_type: The index_type of this DockerProxyAttributes.  # noqa: E501
        :type: str
        """
        allowed_values = ["HUB", "REGISTRY", "CUSTOM"]  # noqa: E501
        if self.local_vars_configuration.client_side_validation and index_type not in allowed_values:  # noqa: E501
            raise ValueError(
                "Invalid value for `index_type` ({0}), must be one of {1}"  # noqa: E501
                .format(index_type, allowed_values)
            )

        self._index_type = index_type

    @property
    def index_url(self):
        """Gets the index_url of this DockerProxyAttributes.  # noqa: E501

        Url of Docker Index to use  # noqa: E501

        :return: The index_url of this DockerProxyAttributes.  # noqa: E501
        :rtype: str
        """
        return self._index_url

    @index_url.setter
    def index_url(self, index_url):
        """Sets the index_url of this DockerProxyAttributes.

        Url of Docker Index to use  # noqa: E501

        :param index_url: The index_url of this DockerProxyAttributes.  # noqa: E501
        :type: str
        """

        self._index_url = index_url

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, DockerProxyAttributes):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, DockerProxyAttributes):
            return True

        return self.to_dict() != other.to_dict()
